config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "application#index"
  post 'import' => "application#import", as: :import
  post 'team-sorting' => "application#team_sorting", as: :team_sorting
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require "#{Rails.root}/lib/import_xcel.rb"
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  require 'csv'
  include ImportXcel
  before_action :set_file,:set_file_data, only: [:import]

  def index
  end

  def import
      header = @data.row(1)
      no_rows = @data.last_row
      if header.present?
        # byebug
        if (no_rows -1 ) < params[:team_count].to_i
          flash[:notice] = "Team count is greater then members"
          redirect_to root_path
        else
          csv_data = get_result(no_rows, params[:team_count],@data, header)
          send_data csv_data, :type => 'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment;filename=testing.xls"

      end
    end
  end

  private
  def set_file
    @file = params[:file]
    if @file.present?
      ext = ["application/vnd.oasis.opendocument.spreadsheet", "text/csv", "application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
      unless ext.include?(@file.content_type)
        flash[:notice] = "Unknown file format!"
        redirect_to root_path
      end
    else
      flash[:notice] = "Add file before form submit"
      redirect_to root_path
    end
  end

  def set_file_data
    # @file = params[:file]
    @data = Roo::Spreadsheet.open(@file.path)
    if @data.last_row <= 1
      flash[:notice] = "Insufficient data!"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/import.js.erb
$('#result').html('<%= @msg %>');
<%#= link_to "Click to here confirm", team_sorting_path(file: @file, header: @header), method: :post %>

app/views/application/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
<div class="file_form">
  <h3>Free Software Foundation of Tamil Nadu</h3>
  <h5>App Dev Boot Camp</h5>
  <h6 style="color: grey">(The file should contain 'Email' and 'College' cloumn)</h6>
  <% if flash[:notice] %>
    <div class="notice" style="color: red"><%= flash[:notice] %></div>
  <% end %>
  <%= form_tag import_path,multipart: true do %>
    <div class="file_form">
      <span id='val'></span>
      <span style="color: grey">Click or Drag the file below!</span>
      <div class= "dropzone">
        <%= file_field_tag :file,id: "file-upload",:required => true%>
      </div>
      <label for="member-count"></label>
      <%= text_field_tag :team_count, nil,:placeholder => "enter member count...", id: "member-count",:required => true %>
     <%= submit_tag "Import" ,class: "button-primary", style: "background-color: lightseagreen"%>
     </div>
  <% end %>
<script>
$('#button').click(function(){
   $("input[type='file']").trigger('click');
})

$("input[type='file']").change(function(){
   $('#val').text(this.value.replace(/C:\\fakepath\\/i, ''))
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamSeparator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>